Progress bar color change indicating HP range
AshtrayShetty/Bootleg-POKeGAME pull request #16
Opened 2020-10-26 22:58 UTC by giribroba

2020-10-27 03:37 UTC, AshtrayShetty commented
Hey!
This PR looks good. But, after the player loses a battle and goes to the next one, on selecting the same pokemon as in the previous battle, the HP bar of that pokemon is red (until the pokemon actually starts attacking).
![Pokémon 27-10-2020 09_02_36](https://user-images.githubusercontent.com/51413934/97254013-7d542f80-1833-11eb-93eb-3a363bb773be.png)

2020-10-27 03:40 UTC, AshtrayShetty requested changes

2020-10-27 03:40 UTC, AshtrayShetty commented on Bootleg-Pokémon/MainWindow.xaml.cs
> +            SetHpColor(_gameSession.CurrentPlayer.ChosenPokemon);
I believe these could be put under the `Move_Click()` function (starts at line 277) as the change occurs after the pokemon attacks.

2020-10-27 04:09 UTC, giribroba commented on Bootleg-Pokémon/MainWindow.xaml.cs
> +            SetHpColor(_gameSession.CurrentPlayer.ChosenPokemon);
Ok, I will make the changes and try again

2020-10-27 04:41 UTC, giribroba commented on Bootleg-Pokémon/MainWindow.xaml.cs
> +            SetHpColor(_gameSession.CurrentPlayer.ChosenPokemon);
> I believe these could be put under the `Move_Click()` function (starts at line 277) as the change occurs after the pokemon attacks.

I try it, but don't work very well. Anyway I make some changes and it's working.

2020-10-28 03:37 UTC, AshtrayShetty commented on Bootleg-Pokémon/MainWindow.xaml.cs
> +            SetHpColor(_gameSession.CurrentPlayer.ChosenPokemon);
The issue still persists, this time for the enemy pokemon.
![Pokémon 28-10-2020 09_05_46](https://user-images.githubusercontent.com/51413934/97387879-e0f65f80-18fc-11eb-82d5-3a87d09b2624.png)

2020-10-28 17:10 UTC, giribroba commented
I think now it's working

2020-10-28 17:55 UTC, AshtrayShetty commented on Bootleg-Pokémon/MainWindow.xaml.cs
> +            SetHpColor(_gameSession.CurrentPlayer.ChosenPokemon);
Everything seems to be resolved now. Good job!!!

2020-10-28 17:56 UTC, merged